version: "3.8"

services:
  backend:
    image: circleci/ruby:2.7.1-node-browsers
    volumes:
      - ./:/var/www
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/local/bundle
    ports:
      - 3000:3000
    tty: true
    user: 1000:1000
    working_dir: /var/www
    environment:
      REDIS_URL: redis://redis:6379
      TEST_REDIS_URL: redis://test_redis:6379
      DISPLAY: unix:0
  redis:
    image: redis:6-alpine
  test_redis:
    image: redis:6-alpine
