version: "3.8"

services:
  backend:
    image: circleci/ruby:2.7.1-node-browsers
    volumes:
      - ./:/var/www
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 3000:3000
    tty: true
    user: 1000:1000
    working_dir: /var/www
    environment:
      DISPLAY: unix:0
